# Generated by Django 4.1 on 2023-05-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sponsor', models.UUIDField()),
                ('nama_brand', models.UUIDField()),
                ('website', models.CharField(max_length=50)),
                ('cp_name', models.CharField(max_length=50)),
                ('cp_email', models.CharField(max_length=50)),
            ],
        ),
    ]
