# Generated by Django 4.1 on 2023-05-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_daftar_sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='nama_brand',
            field=models.CharField(max_length=50),
        ),
    ]
