# Generated by Django 4.1 on 2023-05-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cr_daftar_atlet", "0002_atletkualif"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtletNonKualif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("tanggal_lahir", models.DateField()),
                ("negara_asal", models.CharField(max_length=50)),
                ("play_right", models.BooleanField()),
                ("height", models.IntegerField()),
                ("world_rank", models.IntegerField()),
                ("jenis_kelamin", models.CharField(max_length=50)),
                ("total_point", models.IntegerField()),
            ],
        ),
    ]
