# Generated by Django 4.1 on 2023-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cr_daftar_atlet", "0003_atletnonkualif"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtletGanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_atlet_ganda", models.UUIDField()),
                ("nama_1", models.CharField(max_length=50)),
                ("nama_2", models.CharField(max_length=50)),
                ("total_point", models.IntegerField()),
            ],
        ),
    ]
